spring:
  datasource:
    url: jdbc:mysql://db:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&useSSL=false
    password: docker
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: /Users/rodrigues/Tmp/UploadDir

flyway:
  url: jdbc:mysql://db:3306/
  schemas: rest_with_spring_boot_udemy
  user: root
  password: docker
